---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/8/5 23:17
---

local AttackSession = require("BHElib.sessions.boss.attack_session")

---@class SpellSession:AttackSession
local M = LuaClass("SpellSession", AttackSession)

M.IS_SPELL_CLASS = true

return M