---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/6/1 23:29
---

local BossFight = require("BHElib.units.boss.boss_fight")

---@class BossFight.Nue:BossFight
local M = LuaClass("boss_fight.Nue", BossFight)

---------------------------------------------------------------------------------------------------
---cache variables and functions

local TaskNew = task.New
local Yield = coroutine.yield

---------------------------------------------------------------------------------------------------

local FS = require("file_system")
local _rets = FS.requireScriptsInDirectory({
    "nue_boss_animation",
    "nue_spell1",
}, "enemy")

---@type Prefab.NueAnimation
local _Animation = _rets[1]

local _Spell1 = _rets[2]

---------------------------------------------------------------------------------------------------

function M:ctor()

    local spell_class_array = {
        _Spell1,
    }
    local animation = _Animation()
    animation.x = -100
    animation.y = 300

    TaskNew(self, function()
        local count = 0
        while count < #spell_class_array do
            count = count + 1
            local Spell = spell_class_array[count]
            self.session = Spell(animation)
            while self.session do
                Yield()
            end
        end
        self:setContinueFlag(false)
    end)
end

return M