---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/6/1 23:29
---

local BossFight = require("BHElib.units.boss.single_boss_fight")

---@class BossFight.Nue:BossFight.SingleBossWithSpell
local M = LuaClass("boss_fight.Nue", BossFight)

---------------------------------------------------------------------------------------------------
---cache variables and functions

local TaskNew = task.New
local Yield = coroutine.yield

---------------------------------------------------------------------------------------------------

---@type Prefab.NueAnimation
local _Animation = require("enemy.nue_boss_animation")

local _Spell1 = require("enemy.nue_spell1")
local _Dialogue1 = require("enemy.nue_dialogue")

---------------------------------------------------------------------------------------------------

function M.__create()
    local spell_class_array = {
        _Dialogue1,
        _Spell1,
    }
    local boss = _Animation()
    boss.x = -100
    boss.y = 300
    local self = BossFight.__create(boss, spell_class_array)
    return self
end

return M