---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/3/4 17:08
---

local Stage = require("BHElib.scenes.stage")

---@class SampleStage
local SampleStage = LuaClass("scenes.SampleStage", Stage)
Stage.addStageClass(SampleStage)

function SampleStage:getSceneType()
    return "scene"
end
function SampleStage:getDisplayName()
    return "sample stage"
end
function SampleStage:getSid()
    return "sample_stage"
end

function SampleStage:createScene()
    local scene = display.newScene(self:getSid())
    scene:scheduleUpdateWithPriorityLua(function(dt)
        self:frameFunc(dt)

        self:renderFunc()
    end, 0)
    return scene
end

function SampleStage:cleanup()
end

---------------------------------------------------------------------------------------------------
---testing

local input = require("BHElib.input.input_and_replay")

local TestClass = Class(Object)
TestClass.frame = task.Do
function TestClass:init()
    local scr = require("BHElib.coordinates_and_screen")
    task.New(self, function()
        task.Wait(60)
        for i = 1, 10000000 do
            local w, h = 192 + 96 * sin(i), 224 + 112 * cos(i)
            scr.setPlayFieldBoundary(-w, w, -h, h)
            scr.setOutOfBoundDeletionBoundary(-w - 30, w + 30, -h - 30, h + 30)
            task.Wait(1)
        end
    end)
end
RegisterGameClass(TestClass)

function SampleStage:update(dt)
    self.timer = self.timer + dt
    if self.timer > 1.5 and self.timer < 2.5 then
        local obj = New(TestClass)
        obj.img = "image:test"
    end

    input.refreshDevices(2)
    if input.isAnyDeviceKeyDown("down") then
        for _=1, 9 do
            if ran:Float(0, 1) > 0 then
                local obj = New(Object)
                obj.img = "image:test"
                obj.vx = ran:Float(-4, 4)
                obj.vy = ran:Float(-4, 4)
            end
        end
    end
end


return SampleStage