---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/3/4 17:08
---

local GameScene = require("BHElib.scenes.game_scene")

---@class Menu:GameScene
local Menu = LuaClass("scenes.Menu", GameScene)

---------------------------------------------------------------------------------------------------
---override/virtual

---create and return a new Menu instance
---@return Menu a menu object
function Menu.__create()
    local self = GameScene.__create()
    self.count = 0

    return self
end

function Menu:getSceneType()
    return "menu"
end

function Menu:cleanup()
end

local input = require("BHElib.input.input_and_replay")
function Menu:update(dt)
    self.count = self.count + 1
    if self.count > 180 then
        local Stage = require("BHElib.scenes.game_stage_sample")
        local SceneTransition = require("BHElib.scenes.scene_transition")
        SceneTransition.transitionTo(self, Stage())
    end
    input.refreshDevices(2)
end

local hud_painter = require("BHElib.ui.hud")
function Menu.render(self)
    GameScene.render(self)
    hud_painter.drawHudBackground(
            "image:menu_hud_background",
            1.3
    )
end


return Menu