---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/3/4 17:08
---

local GameScene = require("BHElib.scenes.game_scene")

require("BHElib.scenes.menu.menu_page")

---@class Menu:GameScene
local Menu = LuaClass("scenes.Menu", GameScene)

---------------------------------------------------------------------------------------------------
---override/virtual

---create and return a new Menu instance
---@return Menu a menu object
function Menu.__create()
    local self = GameScene.__create()

    return self
end

local _menu_transition = require("BHElib.scenes.menu.menu_task")

---create a menu scene
---@return cc.Scene a new cocos scene
function Menu:createScene()
    -- initialize by first creating all menu pages

    local main_menu_content = {
        {"Start Game", function()
            task.New(self, function()
                -- fade out menu page
                _menu_transition.transitionTo(self.cur_menu, nil, 30)
                task.Wait(30)

                -- start stage
                local Stage = require("BHElib.scenes.game_stage_sample")
                local SceneTransition = require("BHElib.scenes.scene_transition")
                SceneTransition.transitionTo(self, Stage())
            end)
        end},
    }
    local main_menu = New(SimpleTextMenuPage, "TestMenu", main_menu_content, 1)
    self.cur_menu = _menu_transition.transitionTo(nil, main_menu, 30)

    return GameScene.createScene(self)
end

function Menu:getSceneType()
    return "menu"
end

function Menu:cleanup()
end

local input = require("BHElib.input.input_and_replay")
function Menu:update(dt)
    GameScene.update(self, dt)

    input.refreshDevices(2)
end

local hud_painter = require("BHElib.ui.hud")
function Menu.render(self)
    GameScene.render(self)
    hud_painter.drawHudBackground(
            "image:menu_hud_background",
            1.3
    )
end


return Menu