---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/3/6 0:23
---

local InitState = LuaClass("scenes.InitState")

---create and return a default init state
function InitState.__create()
    local self = {}
    self.random_seed = 0

end