---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/3/6 0:23
---

local InitState = LuaClass("scenes.InitState")

function InitState.__create()
    return {}
end