---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Karl2.
--- DateTime: 2021/3/5 22:40
---

local M = {}

---set to true on the frame the next scene starts
local _transition_flag
local _scene_from
local _scene_to

---------------------------------------------------------------------------------------------------

---setup scene transition at the end of the frame
---@param scene_from GameScene
---@param scene_to GameScene
function M.transitionTo(scene_from, scene_to)
    _scene_from = scene_from
    _scene_to = scene_to

    assert(_scene_from, "ERROR: scene transition, current scene not set!")
    assert(_scene_to, "ERROR: scene transition, next scene not set!")

    local type_from = _scene_from:getSceneType()
    local type_to = _scene_to:getSceneType()
    if type_from == "stage" and type_to == "stage" then
        M.stageToStage(_scene_from, _scene_to)
    elseif type_from == "stage" and type_to == "menu" then
        M.stageToMenu(_scene_from, _scene_to)
    elseif type_from == "menu" and type_to == "stage" then
        M.menuToStage(_scene_from, _scene_to)
    end
end

---return if transitionTo has been called in this frame
---@return boolean true if next scene is ready to replace the current scene
function M.isNextScenePrepared()
    return _transition_flag
end

---------------------------------------------------------------------------------------------------
---swap frame

local director = cc.Director:getInstance()

---should be called at the end of the game frame loop
function M.goToNextScene()
    _scene_from:cleanup()

    -- start the next stage
    local cocos_scene = _scene_to:createScene()
    director:replaceScene(cocos_scene)

    _transition_flag = false
    _scene_from = nil
    _scene_to = nil
end

---------------------------------------------------------------------------------------------------
---go to the next stage

local director = cc.Director:getInstance()

---@param scene_from GameScene
---@param scene_to GameScene
function M.stageToStage(scene_from, scene_to)
    _transition_flag = true
end

---------------------------------------------------------------------------------------------------
---back to menu from stage

---@param scene_from GameScene
---@param scene_to GameScene
function M.stageToMenu(scene_from, scene_to)
    task.New(scene_from, function()
        task.Wait(60)
        _transition_flag = true
    end)
end

---------------------------------------------------------------------------------------------------
---enter a stage

---@param scene_from GameScene
---@param scene_to GameScene
function M.menuToStage(scene_from, scene_to)
    _transition_flag = true
end

return M